const players = [
    {
        Id: "1",
        FirstName: "Matias",
        LastName: "Hänninen",
        UlrName: "string",
        Number: "string",
        Description: "string",
        CategoryId: "Vaihtaja/Etenijä",
        PictureUrl: 'https://fit-technology.fi/wp-content/uploads/2018/09/player1.png',
        PictureHoverUrl: "string",
        AltPictureUrl: "string",
        VideoUrl: "string",
        TimeStamp: "string",
        SponsorLogoUrl: "string",
        SponsorLogoName: "Pohjolan Matka",
        SponsorLinkUrl: "string",
        Visible: true,
        Index: 0
    },
    {
        Id: "2",
        FirstName: "Tuomas",
        LastName: "Jussila",
        UlrName: "string",
        Number: "string",
        Description: "string",
        CategoryId: "Vaihtaja/Etenijä",
        PictureUrl: "https://fit-technology.fi/wp-content/uploads/2018/09/player2.png",
        PictureHoverUrl: "string",
        AltPictureUrl: "string",
        VideoUrl: "string",
        TimeStamp: "string",
        SponsorLogoUrl: "string",
        SponsorLogoName: "Pohjolan Matka",
        SponsorLinkUrl: "string",
        Visible: true,
        Index: 0
    },
    {
        Id: "3",
        FirstName: "Lira",
        LastName: "Kuosa",
        UlrName: "string",
        Number: "string",
        Description: "string",
        CategoryId: "Vaihtaja/Etenijä",
        PictureUrl: "https://fit-technology.fi/wp-content/uploads/2018/09/player3.png",
        PictureHoverUrl: "string",
        AltPictureUrl: "string",
        VideoUrl: "string",
        TimeStamp: "string",
        SponsorLogoUrl: "string",
        SponsorLogoName: "Pohjolan Matka",
        SponsorLinkUrl: "string",
        Visible: true,
        Index: 0
    },
    {
        Id: "4",
        FirstName: "Matias",
        LastName: "Hänninen",
        UlrName: "string",
        Number: "string",
        Description: "string",
        CategoryId: "Vaihtaja/Etenijä",
        PictureUrl: 'https://fit-technology.fi/wp-content/uploads/2018/09/player1.png',
        PictureHoverUrl: "string",
        AltPictureUrl: "string",
        VideoUrl: "string",
        TimeStamp: "string",
        SponsorLogoUrl: "string",
        SponsorLogoName: "Pohjolan Matka",
        SponsorLinkUrl: "string",
        Visible: true,
        Index: 0
    },
    {
        Id: "5",
        FirstName: "Tuomas",
        LastName: "Jussila",
        UlrName: "string",
        Number: "string",
        Description: "string",
        CategoryId: "Vaihtaja/Etenijä",
        PictureUrl: "https://fit-technology.fi/wp-content/uploads/2018/09/player2.png",
        PictureHoverUrl: "string",
        AltPictureUrl: "string",
        VideoUrl: "string",
        TimeStamp: "string",
        SponsorLogoUrl: "string",
        SponsorLogoName: "Pohjolan Matka",
        SponsorLinkUrl: "string",
        Visible: true,
        Index: 0
    },
    {
        Id: "6",
        FirstName: "Lira",
        LastName: "Kuosa",
        UlrName: "string",
        Number: "string",
        Description: "string",
        CategoryId: "Vaihtaja/Etenijä",
        PictureUrl: "https://fit-technology.fi/wp-content/uploads/2018/09/player3.png",
        PictureHoverUrl: "string",
        AltPictureUrl: "string",
        VideoUrl: "string",
        TimeStamp: "string",
        SponsorLogoUrl: "string",
        SponsorLogoName: "Pohjolan Matka",
        SponsorLinkUrl: "string",
        Visible: true,
        Index: 0
    },
    
]

module.exports = players;